"""
PostGIS Database Connection & Models (SQLAlchemy + GeoAlchemy2)
Defines all tables: sensor_readings, events, survivor_reports, 
critical_infrastructure, rescue_zones, resource_units, dispatch_log.
"""

import os
from datetime import datetime
from sqlalchemy import (
    create_engine, Column, Integer, Float, String, Boolean,
    DateTime, Text, Enum as SQLEnum, ForeignKey
)
from sqlalchemy.orm import sessionmaker, declarative_base, relationship
from geoalchemy2 import Geometry
import enum

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://aurora:aurora@localhost:5433/aurora_db"
)

engine = create_engine(DATABASE_URL, echo=False, pool_pre_ping=True)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


# ─── Enums ──────────────────────────────────────────────────────────────
class EventStatus(str, enum.Enum):
    UNVERIFIED = "unverified"
    VERIFIED = "verified"
    FALSE_POSITIVE = "false_positive"
    RESOLVED = "resolved"

class ResourceType(str, enum.Enum):
    AMBULANCE = "ambulance"
    FIRE_TRUCK = "fire_truck"
    POLICE = "police"
    NDRF = "ndrf"

class ResourceStatus(str, enum.Enum):
    AVAILABLE = "available"
    DISPATCHED = "dispatched"
    RETURNING = "returning"

class InfraType(str, enum.Enum):
    HOSPITAL = "hospital"
    SCHOOL = "school"
    FIRE_STATION = "fire_station"
    POLICE_STATION = "police_station"
    SHELTER = "shelter"
    BRIDGE = "bridge"
    WATER_SUPPLY = "water_supply"


# ─── Models ─────────────────────────────────────────────────────────────
class SensorReading(Base):
    """Raw accelerometer/gyroscope readings from Phyphox devices."""
    __tablename__ = "sensor_readings"

    id = Column(Integer, primary_key=True, autoincrement=True)
    device_id = Column(String(64), nullable=False, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    acc_x = Column(Float, nullable=False)
    acc_y = Column(Float, nullable=False)
    acc_z = Column(Float, nullable=False)
    gyr_x = Column(Float)
    gyr_y = Column(Float)
    gyr_z = Column(Float)
    pressure = Column(Float)
    location = Column(Geometry("POINT", srid=4326))
    anomaly_score = Column(Float, default=0.0)


class SeismicEvent(Base):
    """A detected or official earthquake event."""
    __tablename__ = "seismic_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    epicenter = Column(Geometry("POINT", srid=4326), nullable=False)
    magnitude = Column(Float, nullable=False)
    depth_km = Column(Float, default=10.0)
    verified_score = Column(Float, default=0.0)
    status = Column(SQLEnum(EventStatus), default=EventStatus.UNVERIFIED)
    impact_radius_km = Column(Float, default=5.0)
    impact_zone = Column(Geometry("POLYGON", srid=4326))
    source = Column(String(32), default="simulation")  # simulation | imd | usgs


class CriticalInfrastructure(Base):
    """Pune-specific hospitals, schools, fire stations, etc."""
    __tablename__ = "critical_infrastructure"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(256), nullable=False)
    infra_type = Column(SQLEnum(InfraType), nullable=False)
    location = Column(Geometry("POINT", srid=4326), nullable=False)
    capacity = Column(Integer)
    is_operational = Column(Boolean, default=True)
    contact = Column(String(64))


class SurvivorReport(Base):
    """SOS reports from citizens during an event."""
    __tablename__ = "survivor_reports"

    id = Column(Integer, primary_key=True, autoincrement=True)
    event_id = Column(Integer, ForeignKey("seismic_events.id"), index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    location = Column(Geometry("POINT", srid=4326), nullable=False)
    severity = Column(Integer, default=3)  # 1 (minor) to 5 (critical)
    message = Column(Text)
    people_count = Column(Integer, default=1)
    needs_medical = Column(Boolean, default=False)
    is_trapped = Column(Boolean, default=False)
    cluster_id = Column(Integer)  # assigned by DBSCAN


class RescueZone(Base):
    """Zones generated by DBSCAN clustering of survivor reports."""
    __tablename__ = "rescue_zones"

    id = Column(Integer, primary_key=True, autoincrement=True)
    event_id = Column(Integer, ForeignKey("seismic_events.id"), index=True)
    centroid = Column(Geometry("POINT", srid=4326), nullable=False)
    boundary = Column(Geometry("POLYGON", srid=4326))
    priority_score = Column(Float, default=0.0)
    survivor_count = Column(Integer, default=0)
    contains_critical_infra = Column(Boolean, default=False)
    severity = Column(Float, default=0.0)
    anomaly_density = Column(Float, default=0.0)
    distress_density = Column(Float, default=0.0)
    access_difficulty = Column(Float, default=0.0)


class ResourceUnit(Base):
    """Available response units (ambulances, fire trucks, etc.)."""
    __tablename__ = "resource_units"

    id = Column(Integer, primary_key=True, autoincrement=True)
    unit_name = Column(String(128), nullable=False)
    resource_type = Column(SQLEnum(ResourceType), nullable=False)
    location = Column(Geometry("POINT", srid=4326), nullable=False)
    status = Column(SQLEnum(ResourceStatus), default=ResourceStatus.AVAILABLE)
    station_name = Column(String(256))


class DispatchLog(Base):
    """Log of AI-generated dispatch decisions."""
    __tablename__ = "dispatch_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    event_id = Column(Integer, ForeignKey("seismic_events.id"), index=True)
    zone_id = Column(Integer, ForeignKey("rescue_zones.id"))
    unit_id = Column(Integer, ForeignKey("resource_units.id"))
    timestamp = Column(DateTime, default=datetime.utcnow)
    route_geojson = Column(Text)  # GeoJSON LineString of the safe route
    eta_minutes = Column(Float)
    ai_reasoning = Column(Text)  # Gemma 4's justification for the dispatch


# ─── Helpers ────────────────────────────────────────────────────────────
def init_db():
    """Create all tables if they don't exist."""
    Base.metadata.create_all(bind=engine)


def get_db():
    """FastAPI dependency for DB sessions."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
