"""
PostGIS Database Connection & Models (SQLAlchemy + GeoAlchemy2)
Defines all tables: sensor_readings, events, survivor_reports, 
critical_infrastructure, rescue_zones, resource_units, dispatch_log.
"""

import os
from datetime import datetime
from sqlalchemy import (
    create_engine, Column, Integer, Float, String, Boolean,
    DateTime, Text, Enum as SQLEnum, ForeignKey
)
from sqlalchemy.orm import sessionmaker, declarative_base, relationship
from geoalchemy2 import Geometry
import enum

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://aurora:aurora@localhost:5433/aurora_db"
)

engine = create_engine(DATABASE_URL, echo=False, pool_pre_ping=True)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


# ─── Enums ──────────────────────────────────────────────────────────────
class EventStatus(str, enum.Enum):
    UNVERIFIED = "unverified"
    VERIFIED = "verified"
    FALSE_POSITIVE = "false_positive"
    RESOLVED = "resolved"

class ResourceType(str, enum.Enum):
    AMBULANCE = "ambulance"
    FIRE_TRUCK = "fire_truck"
    POLICE = "police"
    NDRF = "ndrf"

class ResourceStatus(str, enum.Enum):
    AVAILABLE = "available"
    DISPATCHED = "dispatched"
    RETURNING = "returning"

class InfraType(str, enum.Enum):
    HOSPITAL = "hospital"
    SCHOOL = "school"
    FIRE_STATION = "fire_station"
    POLICE_STATION = "police_station"
    SHELTER = "shelter"
    BRIDGE = "bridge"
    WATER_SUPPLY = "water_supply"


# ─── Models ─────────────────────────────────────────────────────────────
class SensorReading(Base):
    """Raw accelerometer/gyroscope readings from Phyphox devices."""
    __tablename__ = "sensor_readings"

    id = Column(Integer, primary_key=True, autoincrement=True)
    device_id = Column(String(64), nullable=False, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    acc_x = Column(Float, nullable=False)
    acc_y = Column(Float, nullable=False)
    acc_z = Column(Float, nullable=False)
    gyr_x = Column(Float)
    gyr_y = Column(Float)
    gyr_z = Column(Float)
    pressure = Column(Float)
    location = Column(Geometry("POINT", srid=4326))
    anomaly_score = Column(Float, default=0.0)


class SeismicEvent(Base):
    """A detected or official earthquake event."""
    __tablename__ = "seismic_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    epicenter = Column(Geometry("POINT", srid=4326), nullable=False)
    magnitude = Column(Float, nullable=False)
    depth_km = Column(Float, default=10.0)
    verified_score = Column(Float, default=0.0)
    status = Column(SQLEnum(EventStatus), default=EventStatus.UNVERIFIED)
    impact_radius_km = Column(Float, default=5.0)
    impact_zone = Column(Geometry("POLYGON", srid=4326))
    source = Column(String(32), default="simulation")  # simulation | imd | usgs


class CriticalInfrastructure(Base):
    """Pune-specific hospitals, schools, fire stations, etc."""
    __tablename__ = "critical_infrastructure"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(256), nullable=False)
    infra_type = Column(SQLEnum(InfraType), nullable=False)
    location = Column(Geometry("POINT", srid=4326), nullable=False)
    capacity = Column(Integer)
    is_operational = Column(Boolean, default=True)
    contact = Column(String(64))


class SurvivorReport(Base):
    """SOS reports from citizens during an event."""
    __tablename__ = "survivor_reports"

    id = Column(Integer, primary_key=True, autoincrement=True)
    event_id = Column(Integer, ForeignKey("seismic_events.id"), index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    location = Column(Geometry("POINT", srid=4326), nullable=False)
    severity = Column(Integer, default=3)  # 1 (minor) to 5 (critical)
    message = Column(Text)
    people_count = Column(Integer, default=1)
    needs_medical = Column(Boolean, default=False)
    is_trapped = Column(Boolean, default=False)
    cluster_id = Column(Integer)  # assigned by DBSCAN


class RescueZone(Base):
    """Zones generated by DBSCAN clustering of survivor reports."""
    __tablename__ = "rescue_zones"

    id = Column(Integer, primary_key=True, autoincrement=True)
    event_id = Column(Integer, ForeignKey("seismic_events.id"), index=True)
    centroid = Column(Geometry("POINT", srid=4326), nullable=False)
    boundary = Column(Geometry("POLYGON", srid=4326))
    priority_score = Column(Float, default=0.0)
    survivor_count = Column(Integer, default=0)
    contains_critical_infra = Column(Boolean, default=False)
    severity = Column(Float, default=0.0)
    anomaly_density = Column(Float, default=0.0)
    distress_density = Column(Float, default=0.0)
    access_difficulty = Column(Float, default=0.0)


class ResourceUnit(Base):
    """Available response units (ambulances, fire trucks, etc.)."""
    __tablename__ = "resource_units"

    id = Column(Integer, primary_key=True, autoincrement=True)
    unit_name = Column(String(128), nullable=False)
    resource_type = Column(SQLEnum(ResourceType), nullable=False)
    location = Column(Geometry("POINT", srid=4326), nullable=False)
    status = Column(SQLEnum(ResourceStatus), default=ResourceStatus.AVAILABLE)
    station_name = Column(String(256))


class DispatchLog(Base):
    """Log of AI-generated dispatch decisions."""
    __tablename__ = "dispatch_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    event_id = Column(Integer, ForeignKey("seismic_events.id"), index=True)
    zone_id = Column(Integer, ForeignKey("rescue_zones.id"))
    unit_id = Column(Integer, ForeignKey("resource_units.id"))
    timestamp = Column(DateTime, default=datetime.utcnow)
    route_geojson = Column(Text)  # GeoJSON LineString of the safe route
    eta_minutes = Column(Float)
    ai_reasoning = Column(Text)  # Gemma 4's justification for the dispatch


# ─── Helpers ────────────────────────────────────────────────────────────
def seed_database():
    """Seed the database with default Pune tactical assets and infrastructure if empty."""
    db = SessionLocal()
    try:
        # Seed Resource Units
        unit_count = db.query(ResourceUnit).count()
        if unit_count == 0:
            print("🌱 Seeding Aurora PostGIS database with Pune tactical units...")
            resources = [
                # Ambulances
                ResourceUnit(unit_name="AMB-PUNE-01", resource_type=ResourceType.AMBULANCE, location="POINT(73.8797 18.5308)", status=ResourceStatus.AVAILABLE, station_name="Ruby Hall Clinic"),
                ResourceUnit(unit_name="AMB-PUNE-02", resource_type=ResourceType.AMBULANCE, location="POINT(73.8636 18.5018)", status=ResourceStatus.AVAILABLE, station_name="KEM Hospital"),
                ResourceUnit(unit_name="AMB-PUNE-03", resource_type=ResourceType.AMBULANCE, location="POINT(73.8625 18.5167)", status=ResourceStatus.AVAILABLE, station_name="Sassoon General Hospital"),
                ResourceUnit(unit_name="AMB-PUNE-04", resource_type=ResourceType.AMBULANCE, location="POINT(73.8410 18.5158)", status=ResourceStatus.AVAILABLE, station_name="Sahyadri Hospital"),
                ResourceUnit(unit_name="AMB-PUNE-05", resource_type=ResourceType.AMBULANCE, location="POINT(73.8166 18.4972)", status=ResourceStatus.AVAILABLE, station_name="Deenanath Mangeshkar Hospital"),
                # Fire Trucks
                ResourceUnit(unit_name="FTR-PUNE-01", resource_type=ResourceType.FIRE_TRUCK, location="POINT(73.8553 18.5195)", status=ResourceStatus.AVAILABLE, station_name="Pune Fire Brigade HQ"),
                ResourceUnit(unit_name="FTR-PUNE-02", resource_type=ResourceType.FIRE_TRUCK, location="POINT(73.8697 18.4647)", status=ResourceStatus.AVAILABLE, station_name="Katraj Fire Station"),
                ResourceUnit(unit_name="FTR-PUNE-03", resource_type=ResourceType.FIRE_TRUCK, location="POINT(73.8077 18.5074)", status=ResourceStatus.AVAILABLE, station_name="Kothrud Fire Station"),
                ResourceUnit(unit_name="FTR-PUNE-04", resource_type=ResourceType.FIRE_TRUCK, location="POINT(73.9270 18.5130)", status=ResourceStatus.AVAILABLE, station_name="Hadapsar Fire Station"),
                # NDRF Teams
                ResourceUnit(unit_name="NDRF-PUNE-01", resource_type=ResourceType.NDRF, location="POINT(73.8500 18.5500)", status=ResourceStatus.AVAILABLE, station_name="Baner NDRF Base"),
                ResourceUnit(unit_name="NDRF-PUNE-02", resource_type=ResourceType.NDRF, location="POINT(73.8900 18.5400)", status=ResourceStatus.AVAILABLE, station_name="Yerwada Rescue Depot"),
                ResourceUnit(unit_name="NDRF-PUNE-03", resource_type=ResourceType.NDRF, location="POINT(73.7389 18.5912)", status=ResourceStatus.AVAILABLE, station_name="Hinjewadi Sub-Base"),
                # Police Squads
                ResourceUnit(unit_name="POL-PUNE-01", resource_type=ResourceType.POLICE, location="POINT(73.8474 18.5308)", status=ResourceStatus.AVAILABLE, station_name="Shivajinagar Police HQ"),
                ResourceUnit(unit_name="POL-PUNE-02", resource_type=ResourceType.POLICE, location="POINT(73.8413 18.5171)", status=ResourceStatus.AVAILABLE, station_name="Deccan Police Station"),
                ResourceUnit(unit_name="POL-PUNE-03", resource_type=ResourceType.POLICE, location="POINT(73.8077 18.5074)", status=ResourceStatus.AVAILABLE, station_name="Kothrud Police Station")
            ]
            db.add_all(resources)
            db.commit()

        # Seed Critical Infrastructure
        infra_count = db.query(CriticalInfrastructure).count()
        if infra_count == 0:
            infra_list = [
                CriticalInfrastructure(name="Ruby Hall Clinic", infra_type=InfraType.HOSPITAL, location="POINT(73.8797 18.5308)", capacity=400, is_operational=True),
                CriticalInfrastructure(name="KEM Hospital", infra_type=InfraType.HOSPITAL, location="POINT(73.8636 18.5018)", capacity=600, is_operational=True),
                CriticalInfrastructure(name="Sassoon General Hospital", infra_type=InfraType.HOSPITAL, location="POINT(73.8625 18.5167)", capacity=1200, is_operational=True),
                CriticalInfrastructure(name="Pune Fire Brigade HQ", infra_type=InfraType.FIRE_STATION, location="POINT(73.8553 18.5195)", capacity=10, is_operational=True),
                CriticalInfrastructure(name="Katraj Fire Station", infra_type=InfraType.FIRE_STATION, location="POINT(73.8697 18.4647)", capacity=6, is_operational=True),
                CriticalInfrastructure(name="Shivajinagar Police HQ", infra_type=InfraType.POLICE_STATION, location="POINT(73.8474 18.5308)", capacity=50, is_operational=True),
                CriticalInfrastructure(name="Nehru Stadium Shelter", infra_type=InfraType.SHELTER, location="POINT(73.8553 18.5167)", capacity=2000, is_operational=True),
                CriticalInfrastructure(name="Balewadi Stadium Shelter", infra_type=InfraType.SHELTER, location="POINT(73.7769 18.5645)", capacity=3000, is_operational=True)
            ]
            db.add_all(infra_list)
            db.commit()
            print("✅ Seeding Pune critical infrastructure completed.")
    except Exception as e:
        db.rollback()
        print(f"⚠️ Error seeding database: {e}")
    finally:
        db.close()


def init_db():
    """Create all tables if they don't exist and seed default assets."""
    Base.metadata.create_all(bind=engine)
    seed_database()


def get_db():
    """FastAPI dependency for DB sessions."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
